### ISSUE TITLE
小白不知道怎么在Ubuntu上安装，尴尬了

### ISSUE THREAD

**Issue by imzhengziyi** [Hopetree/django-webstack#1]
请问作者，这个如何安装，有时间可以写一下稍微详细的教程吗？或者来个docker镜像，嘿嘿

**Comment by Hopetree** [comment]
@imzhengziyi 这个是一个Django的应用，安装方式readme里面其实已经很清晰了，这个是不能单独使用的，必须安装后放到Django里面使用。
